version: "3.8"
services:
  frontend:
    build: ./server
    container_name: backend
    ports:
      - '4000:4000'
    volumes:
      - ./server:/app
      - /app/node_modules
  backend:
    build: ./src
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app
      - /app/node_modules
    stdin_open: true